# approve/lgtm commands require additional permissions, so are handled discretely here
name: prow
on:
  issue_comment:
    types: [created]

  # Grant the default GITHUB_TOKEN permission to label issues and review PRs
permissions:
  # allow labels
  issues: write
  # allow adding reviews
  pull-requests: write

jobs:
  review-commands:
    runs-on: ubuntu-latest
    steps:
        - uses: jpmcb/prow-github-actions@v1.1.3
          with:
            prow-commands: |
              /approve
              /lgtm
            github-token: "${{ secrets.GITHUB_TOKEN }}"


            
