name: prow
on:
  schedule:
  - cron: "0 * * * *"

jobs:
  merge-on-approved:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v1.1.3
        with:
          jobs: 'approved'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
