name: "Prow github actions"
on:
  issue_comment:
    types: [created]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v1.1.3
        with:
          prow-commands: |
            /assign
            /unassign
            /retitle
            /area
            /kind
            /priority
            /remove
            /close
            /reopen
            /lock
            /milestone
            /hold
            /cc
            /uncc
          github-token: "${{ secrets.GITHUB_TOKEN }}"
