# auto-apply labels based on configuration
# in $root/.github/labeler.yml
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
